build:
  version: "1.0"

loans:
  message: "Welcome to QuanNvBank loans related product APIs that loaded by file local"
  contactDetails:
    name: "Nguyen Van Quan - Product Owner"
    email: "nguyenvanquan8990@gmail.com"
  onCallSupport:
    - (84)888-22-6666
    - (84)888-33-6666
