services:
  accounts:
    image: "nguyenvanquan/accounts:s4"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - quannvbank
  loans:
    image: "nguyenvanquan/loans:s4"
    container_name: "loans-ms"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - quannvbank
  cards:
    image: "nguyenvanquan/cards:s4"
    container_name: "cards-ms"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - quannvbank
networks:
  quannvbank:
    driver: "bridge"