build:
  version: "3.0"

accounts:
  message: "Welcome to QuanNvBank accounts related local APIs"
  contactDetails:
    name: "Nguyen Van Quan - Developer"
    email: "nguyenvanquan8990@gmail.com"
  onCallSupport:
    - (84)888-22-6666
    - (84)888-33-6666