build:
  version: "2.0"

cards:
  message: "Welcome to QuanNvBank cards related prod APIs"
  contactDetails:
    name: "Nguyen Van Quan - Product Owner"
    email: "nguyenvanquan8990@gmail.com"
  onCallSupport:
    - (84)888-22-6666
    - (84)888-33-6666
