spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to QuanNvBank loans related QA APIs"
  contactDetails:
    name: "Nguyen Van Quan - QA Lead"
    email: "nguyenvanquan8990@gmail.com"
  onCallSupport:
    - (84)888-22-6666
    - (84)888-33-6666
